runtime: nodejs20
entrypoint: node server.js
service: backend

handlers:
  - url: /uploads
    static_dir: uploads

  - url: /brsFiles
    static_dir: brsFiles

  - url: /static
    static_dir: build/static

  - url: /.*
    script: auto
